# Generated by Django 4.0.4 on 2022-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('IdJuego', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable del juego')),
                ('nombreVideojuego', models.CharField(max_length=20, verbose_name='Nombre del videojuego')),
                ('AñoLanzamiento', models.IntegerField(verbose_name='Año de salida del videojuego')),
                ('imagen', models.ImageField(upload_to='videojuegos')),
            ],
        ),
    ]
