# Generated by Django 4.0.4 on 2022-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable de la categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Nombre de la categoria')),
            ],
        ),
    ]
